{% set name = "ctds" %}
{% set version = "1.13.0" %}
{% set sha256 = "8908d0ca292c91aaf8d6c3d35656a4c32b975446ef099ee37441f68b7f17aa3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py build_ext --include-dirs=%PREFIX%\include --library-dirs=%PREFIX%\lib  # [win]
    - python setup.py build_ext --include-dirs=$PREFIX/include --library-dirs=$PREFIX/lib    # [not win]
    - python setup.py install --single-version-externally-managed --record record.txt
  # Due to this requiring stdbool.h and windows C compilers not having C99 Headers
  # disable for now
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - freetds
  run:
    - python
    - freetds
    # package uses pkg_resources
    - setuptools

test:
  imports:
    - ctds
    - ctds.pool

  commands:

about:
  home: https://github.com/zillow/ctds
  license: MIT
  license_file: LICENSE
  summary: DB API 2.0-compliant Linux driver for SQL Server
  license_family: MIT

extra:
  recipe-maintainers:
    - mariusvniekerk
