travis:
  secure:
    BINSTAR_TOKEN: BSSBYVLZ8+/IQQEUYX1EcwqJIRlRhcu9PczLVUBLPOi3Yx1fMRsITw8UBjtfgjLx/n+OOCuuzMIWPC91ifrDLEfmpBdCD7NtqOL6cJD3mUkRUjne3u/PBuFn36XCIcyWTZs6S4LHx3QQF4w61b0nHgjJJ+p0ArLK+WXE6dLv9T19aV+q71p8tcRjbegkVUmtphvgm3GddKTPoSpbTOZRlNGWnFh0P4cG7Yecx36ubmgrA8+NksTVIxCRe6/5m3Yym15X2rmz/qC1xgXwh5E1kiFN9YLhz/6tyW+myFphkT4fLxQQYGVrVCKoB5TdGH9z/x8UHlvuGtmpXf2vdAVZ1vegYy4FmTPNnXYEJe/1gr/Yuj6LPl4w9eVtlHQ/kmu8UlsVSoslhnU7z6sBthKpdWePOrXvUIPPCspKueag0uT/2Fk/z3r+iSOMOfMN0iPkLXkf2Ey5hTd+f6xT8ZJCq+waZJVLr0GIDa1mpGe+dzk3JNdZRP4kEyapLMqDGZYGMv5xRoVaSniROQw1IMR8YKIr7VSdSxlTn5TzlqncFOOJvfgse9xibt0gErvuY5+5KP2GQXDmPhli0EYbabb12DBYWv7dp4aXy+1Z8TAp92vaLcDwJuzeHl3R8PdSEECFeFfwYG2wOj+hHq8+Ti79Y3kWBw+88Xq5Pp5/NP84Png=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
