appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OihguhFuUBjRdBKdo+LKxt/4rRAufDcKuP5t660H3Q5kUXks659V+IZlSMPMy8Hg80+W4h43hBaByR6PEgTaSWPfJdBfQJlylBOqVPmkp+z8jbJo+TrXo+eLtca+5emXIEZPQKrRQus7Ax7YJJix/lrkPnX1RVkz+FiT9dmtXJl9bujJ9Rh9jigvP6tfauCwH8qtg9bs56BbgPNiQNj7MCD6KHcM3QykCFZHf3APDnxxfY7883aycgdBOIoPFAb7Fx0TqA7cqowZPOAKnkoqCr6/FuYyM5S5hrjthSaxEcanHUIuB8vEqoaFUkzTRrP767ezzlUqqHYqKQrFwmTQcVBFZDwFRztliF/1pnFCEiDbrYUIQj7V5LlBx9PRD4dbaD4S0bfCVOOA1HXh2W6p7PDV5zkz+jSqMFLKJbemQJO8rn8b/ahX9YwfYBoWRyA3mhyDdWM2sQNIVhJxQExJUcBfu/yg9XeK//XQT10FGX24YCIpR7mQAc2ljrGOTfXVOyD5T3wOL361b4KTFL5A1wmq2EPrT3Hz0I7KrcXaMrx+90dEEUtsAWb2NfMXRkRStsPdFkWycwQtOr+v9vLgpqkqOa4R4iT+QhjixdglhbO+guMO+xYZ/EvonjBriMD+HUE51F6eYCblKzSHSBEpY5uzWFAm7BLwzLTa/3KTAvI=}
